### ISSUE TITLE
order_by with invalid ordering field raises a server error in FastAPI >=0.100.0

### ISSUE THREAD

**Issue by pavja2** [arthurio/fastapi-filter#437]
I'm having an issue where if I supply an invalid ordering field name to `order_by` in FastAPI version 0.100.0 I get a 500 response with the following shown in the debug logs:
```
ValueError: [TypeError("'ErrorWrapper' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

In FastAPI version 0.99.0 this error does not appear and I get the 422 response that I would expect:
```
{
    "detail": [
        {
            "loc": [
                "order_by"
            ],
            "msg": "asdf is not a valid ordering field.",
            "type": "value_error"
        }
    ]
}
```

Not sure if it's a bug in FastAPI or fastapi-filter but would be curious if there's a workaround or if anyone else can replicate.

<details><summary>Full debug below:</summary>
<p>

```
  File "<path>/my_api/venv/lib/python3.10/site-packages/fastapi_filter/base/filter.py", line 226, in sort
    raise RequestValidationError(e.raw_errors) from e
          └ <class 'fastapi.exceptions.RequestValidationError'>

fastapi.exceptions.RequestValidationError: [ErrorWrapper(exc=ValueError('a is not a valid ordering field.'), loc=('order_by',))]


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<path>/my_api/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 230, in jsonable_encoder
    data = dict(obj)
                └ ErrorWrapper(exc=ValueError('a is not a valid ordering field.'), loc=('order_by',))

TypeError: 'ErrorWrapper' object is not iterable


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<path>/my_api/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 235, in jsonable_encoder
    data = vars(obj)
                └ ErrorWrapper(exc=ValueError('a is not a valid ordering field.'), loc=('order_by',))

TypeError: vars() argument must have __dict__ attribute


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 5
               │     └ 8
               └ <function _main at 0x7fde11df5b40>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 5
           │    └ <function BaseProcess._bootstrap at 0x7fde11de0d30>
           └ <SpawnProcess name='SpawnProcess-1' parent=274995 started>
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7fde11de03a0>
    └ <SpawnProcess name='SpawnProcess-1' parent=274995 started>
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7fde13f9e5c0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=274995 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=274995 started>
    │    └ <function subprocess_started at 0x7fde10d29240>
    └ <SpawnProcess name='SpawnProcess-1' parent=274995 started>
  File "<path>/my_api/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7fde13f9e500>>
  File "<path>/my_api/venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000)>]
           │       │   │    └ <function Server.serve at 0x7fde10cf2050>
           │       │   └ <uvicorn.server.Server object at 0x7fde13f9e500>
           │       └ <function run at 0x7fde114d0af0>
           └ <module 'asyncio' from '/usr/lib/python3.10/asyncio/__init__.py'>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fde10c81d20>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "<path>/my_api/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fddf7dd5630>
  File "<path>/my_api/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fddf76a7e...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fddf76...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x7fde10c4b6a0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fddf7dd5630>
  File "<path>/my_api/venv/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fddf76a7e...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fddf76...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
  File "<path>/my_api/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fddf76a7e...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fddf76...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fddf76c67a0>
          └ <fastapi.applications.FastAPI object at 0x7fde10c4b6a0>
  File "<path>/my_api/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "<path>/my_api/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fddf6d02b00>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fddf76...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x7fddf76c66b0>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fddf76c67a0>
  File "<path>/my_api/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fddf6d02b00>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fddf76...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fddf76c6710>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x7fddf76c66b0>
  File "<path>/my_api/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 88, in __call__
    response = await handler(request, exc)
                     │       └ <starlette.requests.Request object at 0x7fddf76ced10>
                     └ <function request_validation_exception_handler at 0x7fddfbe95ab0>
  File "<path>/my_api/venv/lib/python3.10/site-packages/fastapi/exception_handlers.py", line 25, in request_validation_exception_handler
    content={"detail": jsonable_encoder(exc.errors())},
                       │                │   └ <function ValidationException.errors at 0x7fde1068cc10>
                       │                └ RequestValidationError([ErrorWrapper(exc=ValueError('a is not a valid ordering field.'), loc=('order_by',))])
                       └ <function jsonable_encoder at 0x7fddfbe65000>
  File "<path>/my_api/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 209, in jsonable_encoder
    jsonable_encoder(
    └ <function jsonable_encoder at 0x7fddfbe65000>
  File "<path>/my_api/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 238, in jsonable_encoder
    raise ValueError(errors) from e
                     └ [TypeError("'ErrorWrapper' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

ValueError: [TypeError("'ErrorWrapper' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

</p>
</details>

**Comment by arthurio** [comment]
Looks related to https://github.com/tiangolo/fastapi/discussions/8033#discussioncomment-6627201 I'll take a look when I can but feel free to open up a PR.
